In [2]:
import numpy as np
# Print 20 elements for 1 to 5  with same range
a=np.linspace(1,5,20)
print(a)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [3]:
import numpy as np
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))

[4 6 8]


In [4]:
import numpy as np
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [11]:
import numpy as np
p = np.array([(2, 4, 6), (3, 5, 7)])
print(p.sum(axis=1))
print(np.sqrt(p))

[12 15]
[[1.41421356 2.         2.44948974]
 [1.73205081 2.23606798 2.64575131]]
